SUPPORTED_PERIODS = ["annual", "quarterly"]
DEFAULT_PERIOD = "annual"
MAX_PERIODS = 4

VALID_SIGNALS = {"BUY", "SELL", "NEUTRAL"}
DEFAULT_SIGNAL = "NEUTRAL"

INITIAL_WATCHLIST_TICKERS = ["AAPL", "NVDA", "TSLA", "MSFT"]
